using System;

namespace Exception_Hadiling
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Welcome to Exception handiling");
            //try
            //{
            //    int a = 10;
            //    int b = 2;
            //    int x = a / b;
            //}
            //catch (Exception e) { Console.WriteLine(e); }
            //finally { Console.WriteLine("Finally block is executed"); }
            //Console.WriteLine("Rest of the code");
            //try
            //{
            //    int[] myNumbers = { 1, 2, 3 };
            //    Console.WriteLine(myNumbers[2]);
            //}
            //catch (Exception e)
            //{
            //    Console.WriteLine(e.Message);
            //}
            //try
            //{
            //    Console.WriteLine("Please enter First Number");
            //    int FNO = Convert.ToInt32(Console.ReadLine());
            //    Console.WriteLine("Please enter Second Number");
            //    int SNO = Convert.ToInt32(Console.ReadLine());
            //    int Result = FNO / SNO;
            //    Console.WriteLine("Result = {0}", Result);
            //}
            //catch (FormatException)
            //{
            //    Console.WriteLine("Only numbers are allowed!");
            //}
            //catch (DivideByZeroException)
            //{
            //    Console.WriteLine("Secoond Number cannot be zero");
            //}
            //Console.ReadLine();

            //checked
            ////unchecked
            //{
            //    int val = int.MaxValue;
            //    Console.WriteLine(val + 2);
            //}
        }
    }
}
